baseURL: "https://sangschicom.github.io" 
title: Taeyoung Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: books/
          weight: 5 
        - name: Resume
          url: papers/
          weight: 2
        - name: CV
          url: courses/
          weight: 3
        - name: Blog
          url: https://www.tykim.me
          weight: 6

params:
    description: "This website hosts Taeyoung Kim's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Taeyoung Kim
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Taeyoung Kim
          subtitle: 
          imageUrl: "picture.jpeg"
          hoverImageUrl: "picture2.jpeg"  # 두 번째 이미지 추가
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research Project
              url: research/
            - name: Publication
              url: publication/
            - name: CV/Resume
              url: cv-resume/
            - name: News
              url: news/
            - name: Blog
              url: https://www.tykim.me

    socialIcons:
        # - name: CV
          # url: cv.pdf
        - name: Email
          url: mailto:falcon@yonsei.ac.kr
        # - name: Zoom
          # url: https://www.zoom.us/my/igelfeld
        # - name: Location
          # url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=U3-aG5oAAAAJ
        - name: GitHub
          url: https://github.com/SangsChicom
        # - name: Substack
          # url: https://pmichaillat.substack.com
        # - name: YouTube
          # url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
          # url: https://x.com/pmichaillat
        # - name: Bluesky
          # url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2