name: Overleaf Sync and Compile
on:
  schedule:
    - cron: "0/5 * * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 저장소 체크아웃
    - uses: actions/checkout@v2

    # Overleaf에서 소스 파일 가져오기
    - name: Fetch from Overleaf
      uses: subhamx/overleaf_sync_with_git@master
      with:
        OVERLEAF_PROJECT_ID: ${{ secrets.OVERLEAF_PROJECT_ID }}
        OVERLEAF_COOKIE: ${{ secrets.OVERLEAF_COOKIE }}

    # LaTeX 컴파일 환경 설정
    - name: Setup LaTeX
      uses: xu-cheng/texlive-action@v2
      with:
        packages: 'latexmk texlive-lang-korean'

    # PDF 컴파일
    - name: Compile PDF
      run: |
        cd artifacts
        latexmk -pdf -interaction=nonstopmode main.tex  # main.tex을 실제 메인 파일명으로 변경하세요

    # static/cv 디렉토리 생성 및 PDF 복사
    - name: Copy PDF to static/cv
      run: |
        mkdir -p static/cv
        cp artifacts/*.pdf static/cv/cv.pdf

    # 변경사항 커밋
    - name: Commit changes
      run: |
        git config user.name "Overleaf Sync Bot"
        git config user.email "actions@github.com"
        git add static/cv/cv.pdf
        if [[ $(git diff HEAD --stat) == '' ]]; then 
          echo "No changes to commit"
        else 
          git commit -m "Update CV PDF" && git push
        fi
