name: Overleaf Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Clone Overleaf repository
        run: |
          git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/${{ secrets.OVERLEAF_PROJECT_ID }} overleaf
          
      - name: Install required LaTeX packages
        run: |
          docker run --rm -v $PWD/overleaf:/compile registry.gitlab.com/islandoftex/images/texlive:latest bash -c "
            # main.tex에서 사용된 패키지 추출
            PACKAGES=\$(grep -o '\\\\usepackage{[^}]*}' main.tex | sed 's/\\\\usepackage{//g' | sed 's/}//g' | tr ',' '\n' | tr ' ' '\n' | grep -v '^$')
            
            # 각 패키지 설치
            for pkg in \$PACKAGES; do
              echo \"Installing package: \$pkg\"
              tlmgr install \$pkg || true
            done
          "
          
      - name: Compile LaTeX using Overleaf's Docker image
        run: |
          docker run --rm -v $PWD/overleaf:/compile registry.gitlab.com/islandoftex/images/texlive:latest pdflatex main.tex
          docker run --rm -v $PWD/overleaf:/compile registry.gitlab.com/islandoftex/images/texlive:latest pdflatex main.tex
          
      - name: Copy PDF
        run: |
          mkdir -p static
          cp overleaf/main.pdf static/cv.pdf
          
      - name: Commit and push if changed
        run: |
          git add static/cv.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update CV from Overleaf" && git push)
