name: Overleaf Sync

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        run: |
          rm -rf static/cv.pdf
          
      - name: Fetch latest version from Overleaf
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Download from Overleaf
        run: |
          curl -L -o static/cv.pdf "https://www.overleaf.com/download/project/${{ secrets.OVERLEAF_PROJECT_ID }}/build/$(curl -s -H "Cookie: overleaf_session2=${{ secrets.OVERLEAF_COOKIE }}" https://www.overleaf.com/project/${{ secrets.OVERLEAF_PROJECT_ID }}/builds | jq -r '.builds[0].outputFiles[0].url')"
          
      - name: Commit and push if changed
        run: |
          git add static/cv/cv.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update CV from Overleaf" && git push)
